
create database casestudy
use casestudy

select*from fact
select*from locationn
select*from product1

exec sp_rename 'dbo.location','Locationn'
exec sp_rename 'dbo.product','Product1'


****************************************************************************************************

Q.1 --Display the number of states present in the LocationTable
select count (distinct state) from locationn

Q.2 --How many products are of regular type?
select TYPE, COUNT(product) As Regulat_type from product1
group by Type
or
select COUNT(product) As Regulat_type from product1
where Type='regular'

Q.3 -- How much spending has been done on marketing of product ID 1?
select  SUM(marketing) as Total_cost_Of_Marketing
from fact
where ProductId = 1

Q.4 --What is the minimum sales of a product?
select MIN(Sales) as minimum_sale from fact

Q.5 --Display the max Cost of Good Sold (COGS).
select Max(cogs) as max_sale from fact

Q.6 -- Display the details of the product where product type is coffee.
select productid, product_type, product, type from PRODUCT1
where product_type='coffee'

Q.7 --Display the details where total expenses are greater than 40.
select*from fact
where total_expenses >40

Q.8 -- What is the average sales in area code 719?
select area_code, AVG(sales) as Avg_sale from fact
where Area_Code=719
group by area_code

Q.9 --Find out the total profit generated by Colorado state.
select state, SUM(profit) as Total_profit from fact f inner join locationn l
on f.Area_Code=L.Area_code
where state='colorado'
group by state

Q.10 --Display the average inventory for each product ID.
select productid ,Avg(Inventory) as Arvg_inventory from fact
group by productid


Q.11 --Display state in a sequential order in a Location Table.

select distinct  state as Asc_state from Locationn
order by state Asc --method.1

select state as Asc_state from Locationn 
group by State
order by state Asc --Method.2


Q.12 --Display the average budget of the Product where the average budget margin should be greater than 100.
select productid, avg(budget_profit) as Avg_bud from fact
group by productid
having avg(budget_margin)>100

Q.13 --What is the total sales done on date 2010-01-01?
select SUM(sales)as total_sale from fact
where Date='2010-01-01'

Q.14-- Display the average total expense of each product ID on an individual date.
select productid, date, AVG(total_expenses) as tot_expe from fact
group by date, productid

Q.15--Display the table with the following attributes such as date, productID,product_type, product, sales, profit, state, area_code.
select Date,f.ProductId,profit,sales,product_type,p.Product,l.Area_Code,state 
from fact f inner join Product1 p on f.ProductId=p.ProductId inner join Locationn l 
on l.Area_Code=f.Area_Code 


Q.16 --Display the rank without any gap to show the sales wise rank.
select*, dense_rank() over(order by sales desc) as sales_rank from fact

Q.17--Find the state wise profit and sales.
select state,
sum(f.profit) as to_profit,
sum(f.sales) as to_sales  from fact f inner join locationn l
on f.area_code = l.area_code 
group by state


Q.18--Find the state wise profit and sales along with the product name.
select state,product,
sum(profit) as too_profit,
sum(sales) as too_sales  from fact  inner join locationn 
on fact.Area_Code = locationn.Area_Code inner join product1
on product1.productid=Fact.productid
group by state, Product

19.--If there is an increase in sales of 5%, calculate the increasedsales.
select DATE, productid, sales  ,
(sales*1.05) as increased_sales from fact


Q.20 --Find the maximum profit along with the product ID and producttype.
select f.ProductId, P.Product_Type, max(profit) as max_profit
from fact f inner join product1  p on f.ProductId=P.ProductId
group by f.ProductId, p.Product_Type
order by max_profit desc

Q.21--Create a stored procedure to fetch the result according to the product type
from Product Table.
create proc Product_typeresult
@product_type varchar(50)
As
begin
select productid,Product_type,PRODUCT,TYPE from Product1
where Product_Type=@product_type
end

exec Product_typeresult 'coffee'

select*from fact

Q.22 --Write a query by creating a condition in which if the total expenses is less than 60 then it is a profit or else loss.
Select *, 'ProfiT_loss'=case
when total_expenses <60 then 'Profit'
else 'loss'
end
from fact
Or
select total_Expenses ,
case
when total_Expenses <60 then 'profit'
else 'loss' 
end as pro_loss
from fact

Q.23 --Give the total weekly sales value with the date and product ID details. Use roll-up to pull the data in hierarchical order.

select datepart(year,date) as year_,
datepart(week,date) as week_,
productID,
sum(sales) as tot_sales
from fact
group by rollup (datepart(year,date),datepart(week,date),ProductID)
order by datepart(year,date),datepart(week,date),ProductID

Q.24--Apply union and intersection operator on the tables which consist of attribute area code.

select Area_code from fact
union
Select Area_code from Locationn

select Area_code from fact
intersect
Select Area_code from Locationn

Q.25--Create a user-defined function for the product table to fetch a particular product type based upon the user’s preference.
create function user_prefer
(@pro_type varchar(30))
returns table
as 
return
(select *from product1
where product_type=@pro_type )

Q.26--Change the product type from coffee to tea where product ID is 1 and undo and use 
Begin Transaction 
update product1
set product_type = 'Tea'
where productid = 1
Rollback transaction

Q.27-- Display the date, product ID and sales where total expenses are
between 100 to 200.
Select DATE, Productid, sales, Total_expenses
from fact
where Total_Expenses between 100 and 200

Q.28--Delete the records in the Product Table for regular type. 
begin transaction
delete from Product1
where Type= 'regular'
rollback transaction

Q.29--Display the ASCII value of the fifth character from the columnProduct
select Product,
ASCII (substring (product,5,1) )As fifthcarAscii
from product1
*********************************************************************************************



